#################################
# Version & seed settings
#################################

version: "default"
seed: 0

#################################
# System settings
#################################

T: 1
y0: 0.5

#################################
# Data settings
#################################

n_col: 1024

#################################
# PhysicsInformedNN settings
#################################

n_hidden: 2
n_neurons: 20
activation: 'swish'

#################################
# Training settings
#################################

n_epochs: 10000
learning_rate: 0.001

#################################
# Callback and Log settings
#################################

freq_log: 10
freq_print: 1000
keys_print: ['loss_F']